kind: PersistentVolume
apiVersion: v1
metadata:
  name: masuda-vol
  labels:
    type: local
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/brunokazuaki/k8s
    server: 10.128.0.4
    readOnly: false
