apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-03-04T13:19:59Z
  labels:
    run: nginx
  name: nginx-masuda
  namespace: default
  resourceVersion: "176699"
  selfLink: /api/v1/namespaces/default/services/nginx-masuda
  uid: bd1917ac-1fae-11e8-bce9-42010a800004
spec:
  clusterIP: 10.105.65.158
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
